---
# tasks file for docker-registry
- name: Sign in to DockerHub
  docker_login:
    username: touzria
<<<<<<< HEAD
    password: "{{ dockerhub_password | b64decode | trim }}"
=======
    password: '{{ dockerhub_password | b64decode }}'
>>>>>>> parent of 4824acd (temporarily added clear text passwd for testing purposes)
    reauthorize: yes

- name: Tag and push to docker hub
  community.docker.docker_image:
    name: touzria/angular-app:1.0
    repository: touzria/angular-app:1.0
    tag: 1.0
    push: yes
    source: local