---
# tasks file for docker

- name: Refresh DockerHub credentials
  docker_login:
    username: touzria
<<<<<<< HEAD
    password: "{{ dockerhub_password | b64decode | trim }}"
=======
    password: '{{ dockerhub_password | b64decode }}'
>>>>>>> parent of 4824acd (temporarily added clear text passwd for testing purposes)
    reauthorize: yes

- name: create image docker
  docker_image:
    name: touzria/angular-app:1.0
    build:
     path: /var/lib/jenkins/workspace/{{ repo }}
     pull: no
    source: build
    state: present
    force_source: true
    
- name: run container docker
  docker_container:
    name: angular-app
    image: touzria/angular-app:1.0
    state: started
    recreate: true
    ports:
     - "4200:80"
